Modified te save_page endpoint
Olivernyu/DocDigest pull request #4
Opened 2023-12-16 04:40 UTC by AndrewCzh

Modified the save_page endpoint in the API to allow users to pass 'text' and 'url' parameters. The endpoint now fetches the HTML content of the provided URL, along with the text, stores in the page_data_store.

2023-12-19 17:39 UTC, Olivernyu requested changes
The functional changes look good to me. Can you check the comments i left on `requirements.txt`, there may be some redundant dependencies. Also, could you remove `.DS_Store` from the commits. I assume it got added by mistake.

2023-12-19 17:39 UTC, Olivernyu commented on requirements.txt
> +pydantic~=2.5.2
Is it really necessary to add `pydantic` as a dependency? It is already a dependency of fastapi that gets installed when one installs fastapi.

2023-12-19 17:39 UTC, Olivernyu commented on .DS_Store
Can you remove this file from the commit?

2023-12-19 21:26 UTC, Alex-YuYan requested changes

2023-12-19 21:26 UTC, Alex-YuYan commented on requirements.txt
> +torch~=2.1.2
From our design doc, we don't need to run any model locally, so we probably don't need torch.

2023-12-19 21:26 UTC, Alex-YuYan commented on app/routers/summarize_endpoint.py
> +    summary = summarizer(text, max_length=500, min_length=30, do_sample=False)
According to design doc, we will be using OpenAI API for the summarization. It is ok to have it here for now, but we will probably update it in the future.

2023-12-20 01:40 UTC, AndrewCzh commented on app/routers/summarize_endpoint.py
> +    summary = summarizer(text, max_length=500, min_length=30, do_sample=False)
For sure.

2023-12-20 01:41 UTC, AndrewCzh commented on requirements.txt
> +pydantic~=2.5.2
Delete pydantic and requests.

2023-12-20 04:04 UTC, Olivernyu submitted a review, later dismissed
Thanks for making the changes, LGTM!

2023-12-20 05:14 UTC, Alex-YuYan submitted a review, later dismissed
LGTM. Let's change the summarizer later.

2023-12-20 05:18 UTC, Alex-YuYan submitted a review, later dismissed

2023-12-20 08:46 UTC, Alex-YuYan approved these changes

2023-12-20 10:54 UTC, leo4life2 approved these changes

2023-12-20 10:54 UTC, leo4life2 commented on app/routers/save_endpoint.py
> +    html_content = fetch_html(url)
`fetch_html` could throw an error. consider wrapping this line in a `try ... except` block.

2023-12-20 10:54 UTC, leo4life2 commented on app/routers/summarize_endpoint.py
> +# api_key = os.getenv("OPENAI_API_KEY")
I think we can keep it like this? Or do `os.getenv("OPENAI_API_KEY", "Sample api key")`

2023-12-20 10:54 UTC, merged